#include "AppResourceId.h"

const wchar_t* IDS_BUTTON_ = L"IDS_BUTTON_";
const wchar_t* IDS_BUTTON_LOGIN = L"IDS_BUTTON_LOGIN";
const wchar_t* IDS_BUTTON_REG = L"IDS_BUTTON_REG";
const wchar_t* IDS_MAIN_FORM_CONTACTS = L"IDS_MAIN_FORM_CONTACTS";
const wchar_t* IDS_MAIN_FORM_FRIENDS = L"IDS_MAIN_FORM_FRIENDS";
const wchar_t* IDS_MAIN_FORM_FRIENDS_ONLINE = L"IDS_MAIN_FORM_FRIENDS_ONLINE";
const wchar_t* IDS_MAIN_FORM_I_CONTACTS = L"IDS_MAIN_FORM_I_CONTACTS";
const wchar_t* IDS_MAIN_FORM_MSG = L"IDS_MAIN_FORM_MSG";
const wchar_t* IDS_MAIN_FORM_SEARCH = L"IDS_MAIN_FORM_SEARCH";
const wchar_t* IDS_MAIN_FORM_SETTINGS = L"IDS_MAIN_FORM_SETTINGS";
const wchar_t* IDS_SEARCH = L"IDS_SEARCH";
const wchar_t* IDS_START_SCREEN_DESCR = L"IDS_START_SCREEN_DESCR";
const wchar_t* IDS_STRING1 = L"IDS_STRING1";
const wchar_t* IDS_STRING2 = L"IDS_STRING2";
const wchar_t* IDS_STRING3 = L"IDS_STRING3";
const wchar_t* IDS_STRING4 = L"IDS_STRING4";
const wchar_t* IDS_USERS_IMPORTANT = L"IDS_USERS_IMPORTANT";
